config/routes.rb
BoraAe::Application.routes.draw do
  resources :users

  resources :user_sessions, :only => [:create]
	
	resources :events do
  	collection do
  		get :calendar, :history, :feed_from_facebook
  	end
  end
	
  match 'logout' => 'user_sessions#destroy'
  match 'request_password' => 'user_sessions#request_password'
  match 'channel' => 'facebook#channel'
  

  root :to => 'user_sessions#new'

end

app/views/layouts/_analytics.html.haml
- if Rails.env.production?
	:javascript
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-32824933-1']);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();

app/views/layouts/_facebook.html.haml
#fb-root
:javascript
  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));

app/views/layouts/_menu.html.haml
%menu
	- unless current_user.blank?
		%li
			= link_to calendar_events_path, :class => 'calendar' do
				%span
				Calendário
		%li
			= link_to history_events_path, :class => 'history' do
				%span
				Histórico
		%li
			= link_to logout_path, :class => 'logout' do
				%span
				Sair

app/views/layouts/application.html.haml
!!! 5
%html

	%head
		%title bora.ae
		%meta{ "http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
		= stylesheet_link_tag "application", :media => "all"
		= csrf_meta_tag
		= yield :head
		= render :partial => '/layouts/analytics'
	%body.application
		= render :partial => '/layouts/facebook'
		%header
			= link_to '/', :id => 'logo' do
				= image_tag 'layout/boraae-short.svg', :alt => "bora.ae"
			= render :partial => '/layouts/menu'
		%section.container-fluid
			- if !current_user.blank? && current_user.created_at + 12.hours > Time.now
				%p.flash.badge.badge-info= "Seus dados do facebook estão sendo processados, aguarde..."
			- elsif !flash[:notice].blank?
				%p.flash.badge.badge-success= flash[:notice]
			= yield
		
		/[if lt IE 9]
			= javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
		= javascript_include_tag "application"

app/views/layouts/basic.html.haml
!!! 5
%html

	%head
		%title bora.ae
		%meta{ "http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
		= stylesheet_link_tag "application", :media => "all"
		= csrf_meta_tag
		= yield :head
		= render :partial => '/layouts/analytics'
	%body
		= render :partial => '/layouts/facebook'
		= yield
		
		/[if lt IE 9]
			= javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
		= javascript_include_tag "application"